<?php

return [
    'name' => 'plugins/loyalty-points::email.name',
    'description' => 'plugins/loyalty-points::email.description',
    'templates' => [
        'points_earned' => [
            'title' => 'plugins/loyalty-points::email.points_earned_title',
            'description' => 'plugins/loyalty-points::email.points_earned_description',
            'subject' => 'plugins/loyalty-points::email.points_earned_subject',
            'can_off' => true,
            'enabled' => true,
            'variables' => [
                'customer_name' => 'plugins/loyalty-points::email.customer_name',
                'points_earned' => 'plugins/loyalty-points::email.points_earned',
                'order_code' => 'plugins/loyalty-points::email.order_code',
                'current_balance' => 'plugins/loyalty-points::email.current_balance',
                'level_name' => 'plugins/loyalty-points::email.level_name',
            ],
        ],
        'points_redeemed' => [
            'title' => 'plugins/loyalty-points::email.points_redeemed_title',
            'description' => 'plugins/loyalty-points::email.points_redeemed_description',
            'subject' => 'plugins/loyalty-points::email.points_redeemed_subject',
            'can_off' => true,
            'enabled' => true,
            'variables' => [
                'customer_name' => 'plugins/loyalty-points::email.customer_name',
                'points_redeemed' => 'plugins/loyalty-points::email.points_redeemed',
                'discount_amount' => 'plugins/loyalty-points::email.discount_amount',
                'order_code' => 'plugins/loyalty-points::email.order_code',
                'remaining_balance' => 'plugins/loyalty-points::email.remaining_balance',
            ],
        ],
        'level_upgraded' => [
            'title' => 'plugins/loyalty-points::email.level_upgraded_title',
            'description' => 'plugins/loyalty-points::email.level_upgraded_description',
            'subject' => 'plugins/loyalty-points::email.level_upgraded_subject',
            'can_off' => true,
            'enabled' => true,
            'variables' => [
                'customer_name' => 'plugins/loyalty-points::email.customer_name',
                'new_level_name' => 'plugins/loyalty-points::email.new_level_name',
                'old_level_name' => 'plugins/loyalty-points::email.old_level_name',
                'level_benefits' => 'plugins/loyalty-points::email.level_benefits',
                'earning_rate' => 'plugins/loyalty-points::email.earning_rate',
                'current_balance' => 'plugins/loyalty-points::email.current_balance',
                'lifetime_points' => 'plugins/loyalty-points::email.lifetime_points',
            ],
        ],
        'points_expiring_reminder' => [
            'title' => 'plugins/loyalty-points::email.points_expiring_reminder_title',
            'description' => 'plugins/loyalty-points::email.points_expiring_reminder_description',
            'subject' => 'plugins/loyalty-points::email.points_expiring_reminder_subject',
            'can_off' => true,
            'enabled' => false,
            'variables' => [
                'customer_name' => 'plugins/loyalty-points::email.customer_name',
                'expiring_points' => 'plugins/loyalty-points::email.expiring_points',
                'expiry_date' => 'plugins/loyalty-points::email.expiry_date',
                'current_balance' => 'plugins/loyalty-points::email.current_balance',
            ],
        ],
        'admin_points_earned' => [
            'title' => 'plugins/loyalty-points::email.admin_points_earned_title',
            'description' => 'plugins/loyalty-points::email.admin_points_earned_description',
            'subject' => 'plugins/loyalty-points::email.admin_points_earned_subject',
            'can_off' => true,
            'enabled' => true,
            'variables' => [
                'customer_name' => 'plugins/loyalty-points::email.customer_name',
                'customer_email' => 'plugins/loyalty-points::email.customer_email',
                'points_earned' => 'plugins/loyalty-points::email.points_earned',
                'order_code' => 'plugins/loyalty-points::email.order_code',
                'current_balance' => 'plugins/loyalty-points::email.current_balance',
                'level_name' => 'plugins/loyalty-points::email.level_name',
                'order_url' => 'plugins/loyalty-points::email.order_url',
            ],
        ],
        'admin_points_redeemed' => [
            'title' => 'plugins/loyalty-points::email.admin_points_redeemed_title',
            'description' => 'plugins/loyalty-points::email.admin_points_redeemed_description',
            'subject' => 'plugins/loyalty-points::email.admin_points_redeemed_subject',
            'can_off' => true,
            'enabled' => true,
            'variables' => [
                'customer_name' => 'plugins/loyalty-points::email.customer_name',
                'customer_email' => 'plugins/loyalty-points::email.customer_email',
                'points_redeemed' => 'plugins/loyalty-points::email.points_redeemed',
                'discount_amount' => 'plugins/loyalty-points::email.discount_amount',
                'order_code' => 'plugins/loyalty-points::email.order_code',
                'remaining_balance' => 'plugins/loyalty-points::email.remaining_balance',
                'order_url' => 'plugins/loyalty-points::email.order_url',
            ],
        ],
    ],
];
