export default {
    vue: true,
    js: [
        'discount',
        'order-create',
        { src: 'resources/js/front/checkout.js', out: 'checkout.js' },
        'admin-review',
        { src: 'resources/js/front/order-return.js', out: 'order-return.js' },
        'front-review',
        'front-upsale-crosssale',
        'edit-product',
        'edit-product-collection',
        'global-option',
        'product-option',
        'product-bulk-editable-table',
        'ecommerce-product-attributes',
        'change-product-swatches',
        'change-product-options',
        'currencies',
        'review',
        'shipping',
        'utilities',
        'payment-method',
        'customer',
        'setting',
        'order',
        'order-incomplete',
        'shipment',
        'store-locator',
        'report',
        'dashboard-widgets',
        'avatar',
        'flash-sale',
        'product-label',
        'bulk-import',
        'export',
        'address',
        'tax',
        'invoice',
        'front-ecommerce',
        'product-license-codes',
    ],
    sass: [
        { src: 'resources/sass/ecommerce.scss', out: 'ecommerce.css' },
        { src: 'resources/sass/ecommerce-product-attributes.scss', out: 'ecommerce-product-attributes.css' },
        { src: 'resources/sass/currencies.scss', out: 'currencies.css' },
        { src: 'resources/sass/review.scss', out: 'review.css' },
        { src: 'resources/sass/customer.scss', out: 'customer.css' },
        { src: 'resources/sass/report.scss', out: 'report.css' },
        { src: 'resources/sass/order-return.scss', out: 'order-return.css' },
        { src: 'resources/sass/widget.scss', out: 'widget.css' },
        { src: 'resources/sass/front-auth.scss', out: 'front-auth.css' },
        { src: 'resources/sass/front-ecommerce.scss', out: 'front-ecommerce.css' },
        { src: 'resources/sass/front-ecommerce-missing-bootstrap.scss', out: 'front-ecommerce-missing-bootstrap.css' },
        { src: 'resources/sass/front-ecommerce-rtl.scss', out: 'front-ecommerce-rtl.css' },
        { src: 'resources/sass/front-faq.scss', out: 'front-faq.css' },
        { src: 'resources/sass/front-review.scss', out: 'front-review.css' },
        { src: 'resources/sass/front-theme.scss', out: 'front-theme.css' },
        { src: 'resources/sass/front-theme-rtl.scss', out: 'front-theme-rtl.css' },
        { src: 'resources/sass/front-upsale-crosssale.scss', out: 'front-upsale-crosssale.css' },
    ],
}
