<?php
return [
    'customer_name' => "Customer Name",
    'customer_phone' => 'Customer Phone',
    'customer_address' => 'Customer Address',
    'shipping_method' => 'Shipping Method',
    'payment_method' => 'Payment Method',
    'order_id' => 'Order Id',
    'order_token' => 'Order Token',
    'return_reason' => 'Return Reason',
    'invoice_code' => 'Invoice Code',
    'invoice_link' => 'Invoice Link',
    'enquiry_id' => "Enquiry Code",
    'enquiry_description' => "Enquiry Code",
    'store_name' => "Store Name",
    'store_phone' => "Store Phone",
    'store_link' => 'Store Link',
    'product_name' => "Product Name",
    'withdrawal_amount' => "Withdrawal Amount",
    'product_url' => 'Product Url',
    'verify_link' => 'Verify Link',
    'reset_link' => 'Reset Link',
];
